In [1]:
import numpy as np

In [4]:
arr_1d=np.array([1,3,5,7])
print(arr_1d)

[1 3 5 7]


In [5]:
arr_1d.ndim

1

In [6]:
arr_1d.shape

(4,)

In [7]:
arr_2d=np.array([[1,3,5,7],[2,4,6,8]])
print(arr_2d)

[[1 3 5 7]
 [2 4 6 8]]


In [8]:
arr_2d.size

8

In [9]:
arr_2d.shape

(2, 4)

In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.dtype

dtype('int32')

In [12]:
arr_ones=np.ones([3,5]) #press shift + tab to see signature of method


In [13]:
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
arr_ones.ndim

2

In [15]:
arr_ones.shape

(3, 5)

In [16]:
arr2_ones=np.ones([5,6],dtype=int)
print(arr2_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [18]:
arr_zeros=np.zeros([2,4],dtype=int)
print(arr_zeros)

[[0 0 0 0]
 [0 0 0 0]]


### arange,linspace,reshape,ravel

In [25]:
#np.arange(start,end,steps)
arr1=np.arange(1,36,3)
print(arr1)

[ 1  4  7 10 13 16 19 22 25 28 31 34]


In [26]:
arr1.shape

(12,)

In [23]:
#np.linspace(start-value, end-value, no of values)
arr2=np.linspace(1,18,5)
print(arr2)


[ 1.    5.25  9.5  13.75 18.  ]


In [29]:
arr3=np.reshape(arr1,[2,6])
print(arr3)

[[ 1  4  7 10 13 16]
 [19 22 25 28 31 34]]


In [32]:
arr4=np.reshape(arr1,[4,3])
print(arr4)
arr4.shape

[[ 1  4  7]
 [10 13 16]
 [19 22 25]
 [28 31 34]]


(4, 3)

In [35]:
#ravel- converts multi dim arr to 1d array
arr5=arr4.ravel()

In [36]:
arr5.shape

(12,)

In [37]:
arr4.transpose()

array([[ 1, 10, 19, 28],
       [ 4, 13, 22, 31],
       [ 7, 16, 25, 34]])

### mathematical operations

In [64]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(1,10).reshape(3,3)

In [65]:
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
a1+a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [47]:
np.add(a1,a2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [48]:
a1-a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
np.subtract(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
a1*a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [52]:
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [53]:
a1/a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
#matrix multiplication
a1@a2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [56]:
np.dot(a1,a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [59]:
a1.max() #returns max value


8

In [60]:
a1.argmax() #returns index of max value

8

### note: axis = 0 for col and 1 for row

In [61]:
a1.max(axis=0) #max value from each column

array([7, 8, 9])

In [63]:
a1.max(axis=1) #max value from each row

array([3, 6, 9])

In [66]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a1.min()

1

In [69]:
a1.min(axis=0)

array([1, 2, 3])

In [70]:
a1.sum()

45

In [71]:
a1.sum(axis=1)

array([ 6, 15, 24])

In [72]:
a1.sum(axis=0)

array([12, 15, 18])

In [73]:
a1.mean()

5.0

In [74]:
a1.mean(axis=0)

array([4., 5., 6.])

In [75]:
a1.std() #standard deviation

2.581988897471611

In [76]:
a1.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [77]:
a1.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [79]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [80]:
np.exp(a1) 

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [81]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [82]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

## array slicing

In [83]:
mx=np.arange(1,101).reshape(10,10)

In [84]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [85]:
mx.ndim

2

In [86]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
mx[0].ndim

1

In [91]:
mx[0,0]

1

In [92]:
mx[0,0].ndim

0

In [93]:
mx[1,:] #entire row

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
mx[:,1] #entire column

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [95]:
mx[:,1:3] #selecting multiple columns

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [97]:
mx[1:4,:] #selecting multiple rows

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [99]:
mx[:,:] #selecting entire matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

## concatenate, split


In [102]:
c1=np.arange(1,17).reshape(4,4)
c2=np.arange(17,33).reshape(4,4)

In [103]:
c1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [104]:
c2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [106]:
np.concatenate((c1,c2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [107]:
np.concatenate((c1,c2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [108]:
np.vstack((c1,c2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [109]:
np.hstack((c1,c2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [110]:
np.split(c1,2) #splits array into lists

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [111]:
list1=np.split(c2,2)

In [113]:
list1[0]

array([[17, 18, 19, 20],
       [21, 22, 23, 24]])

### trigonometric functions

In [119]:
np.sin(90)

0.8939966636005579

In [115]:
np.cos(43)

0.5551133015206257

In [120]:
np.sin(180)

-0.8011526357338304

## random

In [121]:
import random

In [126]:
np.random.random() #return value bw 0 and 1

0.5646833229972532

In [135]:
x=np.random.random(3)

In [136]:
x

array([0.62090475, 0.7758118 , 0.47173961])

In [137]:
x.shape

(3,)

In [140]:
x2=np.random.random((3,3))

In [141]:
x2

array([[2.56844302e-01, 1.23843713e-01, 3.07934511e-01],
       [6.27614323e-01, 9.89698200e-01, 5.54190780e-01],
       [7.97839773e-01, 4.91841949e-01, 6.27448344e-04]])

In [142]:
x2.ndim

2

In [143]:
x2.shape

(3, 3)

In [150]:
#randint(start-value, end-value, (size))
np.random.randint(1,10)

2

In [151]:
x3=np.random.randint(1,20,(2,3))

In [152]:
x3

array([[ 1, 11,  3],
       [15, 18,  4]])

In [153]:
np.random.rand(3)

array([0.96580775, 0.81850442, 0.40544484])

In [154]:
np.random.rand(3,3)

array([[0.64874167, 0.33895142, 0.10964005],
       [0.40131296, 0.79362811, 0.93191118],
       [0.28573899, 0.33540654, 0.86273945]])

In [156]:
np.random.randn(4) #return both pos and neg value

array([ 0.15133832, -0.22586928,  0.12063526, -0.24323498])

In [158]:
opt=[1,2,3,4,5]
for i in range(20):
    v=np.random.choice(opt)
    print(v)
    

3
4
5
3
5
3
2
3
5
4
3
3
4
3
1
5
5
1
3
2


In [160]:
np.random.permutation(opt)

array([2, 3, 1, 5, 4])

In [161]:
np.random.permutation(opt)

array([3, 4, 5, 2, 1])